#!/bin/bash
#SBATCH --partition debug
##
#SBATCH --account math751
#SBATCH --time 00:01:00
##SBATCH --mail-user=amara.nusbickel@mail.rit.edu  # Please use YOUR email
#SBATCH --nodes=1
#SBATCH --mail-type=FAIL
#SBATCH --ntasks=16
#SBATCH --cpus-per-task=1
#SBATCH --mem=20G
#SBATCH --job-name=mpi_test
#SBATCH -o stdout.out
#spack load gcc@12.3.1/lhqcen5
#spack load openmpi@4.1.6%gcc@12.3.1/xcunp5q

export OMP_NUM_THREADS=1
srun -n 16 ./test_domain 100 100 4 4
