#!/bin/bash
#SBATCH --partition debug
##
#SBATCH --account math751
#SBATCH --time 00:10:00
##SBATCH --mail-user=amara.nusbickel@mail.rit.edu  # Please use YOUR email
#SBATCH --nodes=1
#SBATCH --mail-type=FAIL
#SBATCH --ntasks=16
#SBATCH --cpus-per-task=1
#SBATCH --mem=250G
#SBATCH --job-name=mpi_test
#SBATCH -o test.out
#spack load gcc@12.3.1/lhqcen5
#spack load openmpi@4.1.6%gcc@12.3.1/xcunp5q

srun -n 16 ./solver3 100 100 4 4
